# Generated by Django 4.0.3 on 2022-04-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Author name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Author last name')),
                ('nationality', models.CharField(max_length=20, verbose_name='Author nationality')),
                ('age', models.PositiveIntegerField(verbose_name='Author age')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
    ]
