# Generated by Django 4.0.3 on 2022-04-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Book title')),
                ('release_date', models.DateField(verbose_name='book release date')),
                ('cover_page', models.ImageField(upload_to='cover')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('author', models.ManyToManyField(to='Authors.authors')),
                ('category', models.ManyToManyField(to='Books.categorys', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Books',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
