# Generated by Django 4.0.3 on 2022-04-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_alter_books_cover_page_alter_books_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='name',
            field=models.CharField(max_length=28, verbose_name='Category name'),
        ),
    ]
