# Generated by Django 4.0.3 on 2022-04-12 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0003_alter_categorys_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='name',
            field=models.CharField(max_length=28, unique=True, verbose_name='Category name'),
        ),
    ]
