# Generated by Django 4.0.3 on 2022-04-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authors', '0001_initial'),
        ('Books', '0004_alter_categorys_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(related_name='author_book', to='Authors.authors'),
        ),
    ]
