# Generated by Django 4.0.3 on 2022-04-05 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Readers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Reader name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Reader last name')),
                ('nationality', models.CharField(max_length=18, verbose_name='Reader nationality')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='Reader age')),
            ],
            options={
                'verbose_name': 'Readers',
                'verbose_name_plural': 'Readerss',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateField(verbose_name='Loan date')),
                ('return_date', models.DateField(verbose_name='Return date')),
                ('returned', models.BooleanField(default=False, verbose_name='Returned')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Books.books', verbose_name='Book')),
                ('lector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Readers.readers', verbose_name='Reader')),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
            },
        ),
    ]
