# Generated by Django 4.0.3 on 2022-04-07 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Readers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='lector',
            new_name='reader',
        ),
    ]
